config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'truyens#new'
  resources :truyens
  resources :comments
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/edittruyen' =>'truyens#list'
  get '/admin' =>'admin#show'
  patch '/truyen/:id' => 'truyens#update'
  post  '/truyen/:id' => 'comments#create'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :truyen
  belongs_to :user
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
    belongs_to :theloai
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to '/'
    
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @theloais=Theloai.all
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
    @theloais=Theloai.all
    @truyens=Truyen.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
      @user = User.find_by_email(params[:session][:email])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to '/'
      else
        redirect_to 'login'
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to '/'
    end
end

app/controllers/truyens_controller.rb
class TruyensController < ApplicationController
  def show
    @theloais = Theloai.all
    @truyen = Truyen.find(params[:id])
    @comments = @truyen.comments
    @comment = Comment.new
  end

  def new
    @truyen = Truyen.new
    @theloais=Theloai.all
  end

  def edit
    @theloais=Theloai.all
    @truyen = Truyen.find(params[:id])
  end

  def list
    @truyens=Truyen.all
  end

  def update
    @truyen = Truyen.find(params[:id])
    if @truyen.update(truyen_params)
      redirect_to '/edittruyen'
    end
  end
  def create
    @truyen = Truyen.new(truyen_params)
    if @truyen.save
      redirect_to '/uptruyen'
    end
  end

  private
  def truyen_params
    params.require(:truyen).permit(:name_vn, :name_en, :content_vn, :content_en, :image, :theloai_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/truyens/edit.html.erb
<h1>Edit Truyện</h1>
<%= form_for(@truyen) do |f| %>
<div class="col-sm-8">
  <p>
    <%= f.label :name_vn  %><br>
    <%= f.text_field :name_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :name_en  %><br>
    <%= f.text_field :name_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_vn  %><br>
    <%= f.text_area :content_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_en  %><br>
    <%= f.text_area :content_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :image_url  %><br>
    <%= f.text_field :image ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :theloai_id  %>
    <h5>điền số ứng với thể loại</h5>
    <ol>
      <% @theloais.each do |t|%>
      <li>
        <%=t.title %>
      </li>
      <%end%>
    </ol>
    <br>
    <%= f.text_field :theloai_id ,class: "form-control"%>
  </p>
  <%= f.submit "UP truyện",class: "btn btn-default" %>
</div>
<% end %>
<a href="<%=themtheloai_path%>" class="btn btn-default">cập nhật thêm thể loại<a>
  <a href="<%=home_path%>" class="btn btn-default">về trang chủ<a>
    <a href="<%=uptruyen_path%>" class="btn btn-default">up thêm truyện<a>
      <a href="<%=admin_path%>" class="btn btn-default">Trang Admin<a>

app/views/truyens/list.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
  <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css"
  rel="stylesheet" type="text/css">

</head>
<body>
  <h2>chọn truyện muốn edit</h2>
  <ol>
    <% @truyens.each do |t| %>
    <li><h4><a href="<%=edit_truyen_path(t)%>"><%= t.name_vn %></a></h4></li>
    <%end%>
  </ol>
</body>

app/views/truyens/new.html.erb
<h1>up Truyện</h1>
<%= form_for(@truyen) do |f| %>
<div class="col-sm-8">
  <p>
    <%= f.label :name_vn  %><br>
    <%= f.text_field :name_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :name_en  %><br>
    <%= f.text_field :name_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_vn  %><br>
    <%= f.text_area :content_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_en  %><br>
    <%= f.text_area :content_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :image_url  %><br>
    <%= f.text_field :image ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :theloai_id  %>
    <h5>điền số ứng với thể loại</h5>
    <ol>
      <% @theloais.each do |t|%>
      <li>
        <%=t.title %>
      </li>
      <%end%>
    </ol>
    <br>
    <%= f.text_field :theloai_id ,class: "form-control"%>
  </p>
  <%= f.submit "UP truyện",class: "btn btn-default" %>
</div>
<% end %>
<a href="<%=themtheloai_path%>" class="btn btn-default">cập nhật thêm thể loại<a>
  <a href="<%=home_path%>" class="btn btn-default">về trang chủ<a>
    <a href="<%=admin_path%>" class="btn btn-default">Trang Admin<a>

app/views/truyens/show.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
  <link href="truyenmoi.css" rel="stylesheet" type="text/css">
</head>

<body>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span>Brand</span></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-ex-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
              <a href="<%= home_path %>">Trang Chủ<i class="fa fa-border fa-home pull-left"></i></a>
            </li>
            <li>
              <a href="<%= new_path %>">Truyện Mới Cập Nhật</a>
            </li>
            <li>
              <a href="#">Tất Cả Các Truyện</a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-expanded="false">Thể Loại<br><i class="fa fa-caret-down pull-right"></i></a>
              <ul class="dropdown-menu" role="menu">
                <% @theloais.each do |t|%>
                <li>
                  <a href="<%= theloai_path(t) %>"><%= t.title%></a>
                </li>
                <%end%>
              </ul>
            </div>
          </div>
        </div>
        <div class="navbar navbar-default navbar-fixed-top navbar-inverse">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-ex-collapse">
              <ul class="nav navbar-left navbar-nav">
                <li class="active">
                  <a href="<%= home_path %>">Trang Chủ<i class="fa fa-border fa-home pull-left"></i></a>
                </li>
                <li>
                  <a href="<%= new_path %>">Truyện Mới Cập Nhật</a>
                </li>
                <li>
                  <a href="#">Tất Cả Các Truyện</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                  aria-expanded="false">Thể Loại<br><i class="fa fa-caret-down pull-right"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <% @theloais.each do |t|%>
                    <li>
                      <a href="<%= theloai_path(t) %>"><%= t.title%></a>
                    </li>
                    <%end%>
                  </ul>
                </li>
                <% if current_user %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                  aria-expanded="false"><%= current_user.email %><br><i class="fa fa-caret-down pull-right"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="<%= logout_path%>">log out</a>"</li>
                  </ul>
                </li>
              </ul>
              <% else %>
            </ul>
            <% end %>
          </ul>
          <form class="navbar-form navbar-right text-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Tìm Truyện</button>
          </form>
          <p class="navbar-right navbar-text">Truyện Song &nbsp;Ngữ
            <br>
          </p>
          <% if current_user %>
          <% else %>
          <a class="btn btn-default navbar-btn navbar-left" data-toggle="modal" href="<%=login_path%>"><i class="fa fa-star fa-fw"></i>Đăng Nhập</a>
          <%end%>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="background-image" style="background-image : url('http://studiohartistgroup.com/wp-content/uploads/2013/06/bg3.jpg')"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h1 class="text-info text-left">
              <i class="fa fa-star fa-fw"></i>
              <b>
                <i>Truyện Song Ngữ Anh - Việt</i>
              </b>
              <br>
            </h1>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <hr>
    </div>
    <div class="col-md-12"></div>
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h1 class="panel-title text-warning"><%= @truyen.name_vn%> <%= @truyen.name_en%></h1>
              </div>
              <div class="panel-body">
                <p class="text-center">Thời điểm cập nhật:
                  <br>
                  <br>
                </p>
                <p class="text-center"><%= @truyen.created_at%></p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="btn-group btn-group-lg" data-toggle="buttons">
              <a class="active btn btn-warning dropdown-toggle" data-toggle="button"> CHỌN NGÔN NGỮ </a>
              <ul class="dropdown-menu" role="menu">
                <li>Tiếng Việt</li>
                <li>English</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <h2 class="text-center text-warning">Ngôn ngữ hiện tại</h2>
    <div class="section">
      <div class="background-image"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p class="text-justify">
              <%= @truyen.content_vn%></p>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade">
        <div class="modal-dialog"></div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading"></div>
      </div>
      <footer class="section section-primary">
        <div class="background-image"></div>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <h2 class="panel-title text-left">
                    <i class="fa fa-star fa-fw"></i>Bình luận.</h2>
                  </div>
                  <div class="panel-body">
                    <%= form_for (@comment) do |f| %>
                      <p>
                        <%= f.text_field :content ,class: "form-control"%>
                      </p>
                      <%= f.submit "Gửi bình luận",class: "btn btn-lg btn-success" %>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <% @comments.each do |c|%>
                <div class="panel panel-primary">
                  <div class="panel-heading"></div>
                  <div class="panel-body">
                    <%= c.content%><br>
                    <p class=text-right><%= c.created_at%><p>
                  </div>
                </div>
                  <% end %>
              </div>
            </div>
          </div>
        </footer>
        <div class="section text-right">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="col-xs-3 text-center">
                  <a><i class="fa fa-3x fa-fw fa-instagram fa-pulse text-info"></i></a>
                  <a><i class="fa fa-3x fa-fw fa-pulse fa-twitter pull-right text-info"></i></a>
                </div>
                <div class="col-xs-3 text-center">
                  <a><i class="fa fa-3x fa-fw fa-github fa-pulse text-info"></i></a>
                  <a><i class="fa fa-3x fa-facebook fa-fw fa-pulse pull-left text-info"></i></a>
                </div>
                <a href="#"><i class="fa fa-5x fa-arrow-circle-o-up text-success"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="section">
          <div class="background-image" style="background-image : url('https://unsplash.imgix.net/uploads/14129863345840df499fc/0165574c?w=1024&amp;q=50&amp;fm=jpg&amp;s=6e5127e797feb9b5a72f7ae4a0f3a89b')"></div>
          <div class="container">
            <div class="row">
              <div class="col-md-12 text-center">
                <ul class="pagination">
                  <li>
                    <a href="#">Trang Trước</a>
                  </li>
                  <li>
                    <a href="#">1</a>
                  </li>
                  <li>
                    <a href="#">2</a>
                  </li>
                  <li>
                    <a href="#">3</a>
                  </li>
                  <li>
                    <a href="#">4</a>
                  </li>
                  <li>
                    <a href="#">5</a>
                  </li>
                  <li>
                    <a href="#">Trang Sau</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="section">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="text-center">FAM</h1>
                <p class="text-center">We are a group of University of Engineering and Technology
                  <br>
                </p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-1">
                <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
                class="img-circle img-responsive">
              </div>
              <div class="col-md-2">
                <h3 class="text-left">Ngô Hải Yến</h3>
                <p class="text-left">K60-CD</p>
              </div>
              <div class="col-md-1">
                <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
                class="img-circle img-responsive">
              </div>
              <div class="col-md-2">
                <h3 class="text-left">Bùi Diệu Linh</h3>
                <p class="text-left">K60-CB</p>
              </div>
              <div class="col-md-1">
                <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
                class="img-circle img-responsive">
              </div>
              <div class="col-md-2">
                <h3 class="text-left">Đinh Khắc Quý</h3>
                <p class="text-left">K60-CAC
                  <br>
                </p>
              </div>
              <div class="col-md-1">
                <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
                class="img-circle img-responsive">
              </div>
              <div class="col-md-2">
                <h3 class="text-left">Vũ Hoàng Long</h3>
                <p class="text-left">K60-CAC</p>
              </div>
            </div>
          </div>
        </div>
      </body>
      </html>

app/views/users/new.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
  <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css"
  rel="stylesheet" type="text/css">

</head>

<body>
  <h1>Sign Up</h1>
  <%= form_for(@user) do |f| %>
  <%= f.text_field :first_name, :placeholder => "First name" %>
  <%= f.text_field :last_name, :placeholder => "Last name" %>
  <%= f.email_field :email, :placeholder => "Email" %>
  <%= f.password_field :password, :placeholder => "Password" %>
  <%= f.submit "Create an account", class: "btn-submit" %>
  <% end %>
</body>

</html>