config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'truyens#new'
  resources :truyens
  resources :comments
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/edittruyen' =>'truyens#list'
  get '/admin' =>'admin#show'
  patch '/truyen/:id' => 'truyens#update'
  post  '/truyen/:id' => 'comments#create'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :truyen
  belongs_to :user
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
    belongs_to :theloai
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @theloais=Theloai.all
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
    @theloais=Theloai.all
    @truyens=Truyen.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/show.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
  <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css"
  rel="stylesheet" type="text/css">

</head>
<body>
  <ul>
    <li>
      <a href="<%=themtheloai_path%>" class="active"><h1>cập nhật thêm thể loại</h1><a>
      </li>
      <li>
        <a href="<%=edittruyen_path%>" class="active"><h1>Chỉnh Sửa Truyện</h1><a>
        </li>
        <li>
          <a href="<%=uptruyen_path%>" class="active"><h1>up thêm truyện</h1><a>
          </li>
          <li>
            <a href="<%=signup_path%>" class="active"><h1>dang ky</h1><a>
            </li>
            <li>
              <a href="<%=login_path%>" class="active"><h1>dang nhap</h1><a>
              </li>
              <li>
                <a href="<%=home_path%>" class="active"><h1>về trang chủ</h1><a>
                </li>
              </ul>
            </body>
            <html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Truyensongngu7</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>